[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\n/home/peng)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xff\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xff\0\0\0\0\0\0\0\0\x5V\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xff)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(659 627)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/peng/2025-10-26%2021-30-32.mp4
times=7650
