[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
padding = { x = 8, y = 6 }
dynamic_padding = true
# decorations = "full"
decorations = "buttonless"
title = "Alacritty@CachyOS"
opacity = 0.8
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
# 使用 Nord 主题
draw_bold_text_with_bright_colors = true
[colors.primary]
background = "0x1E1E2E"
foreground = "0xCDD6F4"

[colors.cursor]
text = "0x1E1E2E"
cursor = "0xF5E0DC"

[colors.selection]
text = "0x1E1E2E"
background = "0xF5E0DC"

[colors.normal]
black   = "0x45475A"
red     = "0xF38BA8"
green   = "0xA6E3A1"
yellow  = "0xF9E2AF"
blue    = "0x89B4FA"
magenta = "0xF5C2E7"
cyan    = "0x94E2D5"
white   = "0xBAC2DE"

[colors.bright]
black   = "0x585B70"
red     = "0xF38BA8"
green   = "0xA6E3A1"
yellow  = "0xF9E2AF"
blue    = "0x89B4FA"
magenta = "0xF5C2E7"
cyan    = "0x94E2D5"
white   = "0xA6ADC8"

[font]
size = 13

[font.normal]
family = "JetBrains Mono Nerd Font Propo"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font Propo"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font Propo"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font Propo"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "beam"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
